stages:
  - lint
  - generate

lint:
  stage: lint
  image:
    name: bufbuild/buf:1.17.0
    entrypoint: [""]
  script:
    - buf lint
  tags:
    - docker
  needs: [ ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  interruptible: true
  timeout: 5m

breaking:
  stage: lint
  image:
    name: bufbuild/buf:1.17.0
    entrypoint: [""]
  script:
    - buf breaking --against '.git#branch=main'
  tags:
    - docker
  needs: [ ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "main"
  interruptible: true
  timeout: 5m

#generate:protobuf:
#  stage: generate
#  image:
#    name: bufbuild/buf:1.17.0
#    entrypoint: [""]
#  script:
#    - buf generate
#  artifacts:
#    paths:
#      - gen/python
#    expire_in: 1 week
#  tags:
#    - docker
#  needs: []
#  interruptible: true
#  timeout: 15m

buf:push:
  stage: generate
  image:
    name: bufbuild/buf:1.17.0
    entrypoint: [""]
  script:
    - buf build
    - echo $BUF_LOGIN_TOKEN | buf registry login --username $BUF_LOGIN_USERNAME --token-stdin
    - buf push
  tags:
    - docker
  needs: []
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
  interruptible: true
  timeout: 15m