stages:
  - lint
  - generate

lint:
  stage: lint
  image:
    name: bufbuild/buf:latest
    entrypoint: [""]
  script:
    - buf lint
  tags:
    - gitlab-org-docker
  needs: [ ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  interruptible: true
  timeout: 5m

breaking:
  stage: lint
  image:
    name: bufbuild/buf:latest
    entrypoint: [""]
  script:
    - git pull origin main
    - buf breaking --against '.git#branch=origin/main'
  tags:
    - gitlab-org-docker
  needs: [ ]
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH != "main"
  interruptible: true
  timeout: 5m

generate:protobuf:python:
  stage: generate
  image:
    name: bufbuild/buf:latest
    entrypoint: [""]
  script:
    - buf generate --include-imports
  artifacts:
    name: "generate-python-$CI_COMMIT_SHA"
    paths:
      - gen/python
  tags:
    - gitlab-org-docker
  needs: []
  interruptible: true
  timeout: 15m

generate:protobuf:go:
  stage: generate
  image:
    name: bufbuild/buf:latest
    entrypoint: [""]
  script:
    - buf generate --include-imports
  artifacts:
    name: "generate-go-$CI_COMMIT_SHA"
    paths:
      - gen/go
  tags:
    - gitlab-org-docker
  needs: []
  interruptible: true
  timeout: 15m

buf:push:
  stage: generate
  image:
    name: bufbuild/buf:latest
    entrypoint: [""]
  script:
    - buf build
    - buf push
  tags:
    - gitlab-org-docker
  needs:
    - lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
  interruptible: true
  timeout: 15m
